image: nixos/nix:latest

before_script:
- export LC_ALL=C.UTF-8
- nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs
- nix-channel --update
- nix-env -iA nixpkgs.cachix
- nix-env -iA nixpkgs.stack
- nix-env -iA nixpkgs.hlint

stages:
- build
- test

build:
  stage: build
  script:
  - stack --nix build --ghc-options "-Wall -Werror"

test:
  stage: test
  script:
  - stack --nix test --ghc-options "-Wall -Werror"
